name: Build and deploy Node.js app to Azure Web App - airtrexrequests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: 📦 Install, build, and prune
        run: |
          npm ci
          npm run build
          npm prune --omit=dev
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}

      - name: 📂 Prepare deployment package
        run: |
          mkdir -p deploy/.next/static
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/static
          cp -r public deploy/public
          cp next.config.js deploy/ || true
          echo '#!/bin/sh
          cd /home/site/wwwroot
          PORT=8080 node server.js
          chmod +x deploy/startup.sh
          cd deploy
          zip -r ../release.zip .
          cd ..

      - name: 📤 Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: 📥 Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 📦 Unzip release
        run: unzip release.zip

      - name: 🚀 Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'airtrexrequests'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8F1A663139A6471BBB0B85FEBF386A29 }}
